baseURL = "https://www.heroicpantheon.com"
title = "Heroic Pantheon"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Your site description"
  copyright = "Copyright © 2021 Your Name"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true

[[menu.main]]
name = "Stolen Lands Map"
url = "stolenlands.html"
weight = 50
